import React, { useState, useCallback } from 'react';
import { Modal, Button, Input } from 'antd';
import { FiLink, FiCopy, FiCheck, FiMail } from 'react-icons/fi';
import { toast } from 'react-toastify';
import dayjs from 'dayjs';
import { useTheme } from '../../context/ThemeContext';
import boxScheduleService from '../../services/boxScheduleService';

const ShareScheduleModal = ({ open, onClose, scheduleDays = [], scheduleTypes = [] }) => {
  const { colors } = useTheme();
  const [shareUrl, setShareUrl] = useState('');
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [textCopied, setTextCopied] = useState(false);

  const handleGenerateLink = useCallback(async () => {
    setGenerating(true);
    try {
      const data = await boxScheduleService.generateShareLink();
      const result = data.data || {};
      const fullUrl = `${window.location.origin}${result.shareUrl}`;
      setShareUrl(fullUrl);
    } catch (err) {
      toast.error('Failed to generate link');
    } finally { setGenerating(false); }
  }, []);

  const handleCopyLink = () => {
    if (!shareUrl) return;
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    toast.success('Link copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyAsText = () => {
    const typeCounters = {};
    const allDays = [];
    scheduleDays.forEach((day) => {
      [...(day.calendarDays || [])].sort((a, b) => a - b).forEach((cd) => allDays.push({ ...day, singleDate: cd }));
    });
    allDays.sort((a, b) => a.singleDate - b.singleDate);

    let text = `PRODUCTION SCHEDULE\nPrepared: ${dayjs().format('MMMM D, YYYY')}\n\n`;
    text += `DAY  |  DATE           |  TYPE       |  DETAILS\n`;
    text += `-----+------------------+-------------+------------------\n`;

    allDays.forEach((day) => {
      if (!typeCounters[day.typeName]) typeCounters[day.typeName] = 0;
      typeCounters[day.typeName]++;
      const num = day.typeName === 'Day Off' ? '  \u2014' : String(typeCounters[day.typeName]).padStart(3);
      const date = dayjs(day.singleDate).format('ddd, MMM DD').padEnd(16);
      const type = (day.typeName === 'Day Off' ? 'DAY OFF' : day.typeName.toUpperCase()).padEnd(11);
      text += ` ${num}  |  ${date}|  ${type}  |  ${day.title || ''}\n`;
    });

    text += `\n---\nGenerated by Zillit \u2014 ${dayjs().format('MMMM D, YYYY')}`;

    navigator.clipboard.writeText(text);
    setTextCopied(true);
    toast.success('Schedule copied as text \u2014 paste into email');
    setTimeout(() => setTextCopied(false), 2000);
  };

  return (
    <Modal open={open} onCancel={onClose} centered width={480}
      title={<span style={{ fontSize: '16px', fontWeight: '700' }}>
        <FiLink size={16} style={{ marginRight: '8px', verticalAlign: 'middle' }} />
        Share Schedule
      </span>}
      footer={<Button onClick={onClose} style={{ borderRadius: '6px' }}>Close</Button>}>
      <div style={{ padding: '8px 0' }}>

        {/* Option 1: Shareable Link */}
        <div style={{
          padding: '16px', background: colors.surfaceAlt, border: `1px solid ${colors.border}`,
          borderRadius: '8px', marginBottom: '16px',
        }}>
          <div style={{ fontSize: '13px', fontWeight: '600', color: colors.textBody, marginBottom: '8px' }}>
            <FiLink size={14} style={{ marginRight: '6px', verticalAlign: 'middle' }} />
            Share via Link
          </div>
          <p style={{ fontSize: '12px', color: colors.textMuted, margin: '0 0 12px' }}>
            Generate a read-only link that anyone can use to view the schedule.
          </p>

          {shareUrl ? (
            <div className="flex gap-2">
              <Input value={shareUrl} readOnly style={{ flex: 1, borderRadius: '6px', fontSize: '12px' }} />
              <Button icon={copied ? <FiCheck size={13} /> : <FiCopy size={13} />} onClick={handleCopyLink}
                style={{ borderRadius: '6px', borderColor: copied ? colors.successText : colors.borderButton, color: copied ? colors.successText : colors.textSecondary }}>
                {copied ? 'Copied' : 'Copy'}
              </Button>
            </div>
          ) : (
            <Button icon={<FiLink size={13} />} onClick={handleGenerateLink} loading={generating}
              style={{ borderRadius: '6px', borderColor: colors.solidDark, color: colors.solidDark, fontWeight: '600' }}>
              Generate Link
            </Button>
          )}
        </div>

        {/* Option 2: Copy as Text */}
        <div style={{
          padding: '16px', background: colors.surfaceAlt, border: `1px solid ${colors.border}`,
          borderRadius: '8px',
        }}>
          <div style={{ fontSize: '13px', fontWeight: '600', color: colors.textBody, marginBottom: '8px' }}>
            <FiMail size={14} style={{ marginRight: '6px', verticalAlign: 'middle' }} />
            Copy as Text (for Email)
          </div>
          <p style={{ fontSize: '12px', color: colors.textMuted, margin: '0 0 12px' }}>
            Copy the schedule as plain text \u2014 paste into any email or message.
          </p>
          <Button icon={textCopied ? <FiCheck size={13} /> : <FiCopy size={13} />} onClick={handleCopyAsText}
            style={{ borderRadius: '6px', borderColor: textCopied ? colors.successText : colors.borderButton, color: textCopied ? colors.successText : colors.textSecondary }}>
            {textCopied ? 'Copied' : 'Copy Schedule as Text'}
          </Button>
        </div>
      </div>
    </Modal>
  );
};

export default ShareScheduleModal;
